env:
  browser: true
  es6: true
  jquery: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
    "no-restricted-globals": ["error", "event", "fdescribe"],
    # I really don't like that style
    # "nonblock-statement-body-position": "off"
}
