before_script:
    - apt-get update -y
    - apt-get install -y python-pip python-dev build-essential mariadb-client libmysqlclient-dev
    - pip install -r requirements.txt

job1:
    script: "test.sh"
