version: '3'
services:
#    mariadb:
#        image: mariadb
#        restart: always
#        environment:
#            MYSQL_ROOT_PASSWORD: rootpw
#            MYSQL_DATABASE: FilmLog
#            MYSQL_USER: filmlog
#            MYSQL_PASSWORD: filmlogpw
#        volumes:
#            - db_data:/var/lib/mysql
#        ports:
#            - "3306:3306"
    filmlog:
        depends_on:
            - mariadb
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./filmlog:/srv/filmlog.org/filmlog/
#        environment:
#            FILMLOG_DB_URL: mysql+mysqldb://filmlog:filmlogpw@mariadb/filmlog?charset=utf
volumes:
    db_data:
