ALTER TABLE FilmTests
MODIFY COLUMN headHeight SMALLINT UNSIGNED,
MODIFY COLUMN expLog DECIMAL (3,2) UNSIGNED AS (ROUND(LOG10(lux * exposureTime * 1000), 2)) VIRTUAL;

ALTER TABLE DevRecipes
CHANGE COLUMN description notes TEXT;

ALTER TABLE DevRecipes
ADD COLUMN rotaryRPM TINYINT UNSIGNED DEFAULT NULL AFTER agitation;
