SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE Papers
  ADD UNIQUE user_name (userID, name);

ALTER TABLE Cameras
  ADD COLUMN loadedFilmTypeID SMALLINT UNSIGNED DEFAULT NULL AFTER cameraID,
  ADD COLUMN notes TEXT DEFAULT NULL AFTER name,
  ADD CONSTRAINT Cameras_FilmTypes_fk
    FOREIGN KEY (userID, loadedFilmTypeID) REFERENCES FilmTypes (userID, filmTypeID)
    ON DELETE RESTRICT ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;
